select_parent_methods = ["roulette" "rank" "tournament-rep" "tournament-norep"];
proba_parent_asign_methods = ["lin-rank" "exp-rank"];
cross_over_method = ["PMX" "cycle"];
survivor_select_method = ["age" "genitor"];
mutations = ["exchange" "shake" "none"];

N = input('Select N (NO.Cityes): ');

% ----------------------------
% --------Gridsearch----------
% ----------------------------
for spm = select_parent_methods
    for com = cross_over_method
        for ssm = survivor_select_method
            for m = mutations
                if strcmp(spm, "rank")
                    for ppam = proba_parent_asign_methods
                        rng(12345);
                        genetic = Genetic( ...
                            N, ... 
                            20, ... 
                            spm, ... 
                            com, ... 
                            ssm, ... 
                            m, ...
                            ppam ...
                        );
                        genetic = run(genetic, 1, 30);
                    end
                else 
                    rng(12345);
                    genetic = Genetic( ...
                        N, ... 
                        20, ... 
                        spm, ... 
                        com, ... 
                        ssm, ... 
                        m ...
                    );
                    genetic = run(genetic, 1, 30);
                end
            end
        end
    end
end

% --------Parameters----------

% ----------------------------
% --------Population----------
% ----------------------------
population = [20 60 100 260 500 800];
for pop = population
    rng(12345);
    genetic = Genetic( ...
        N, ... 
        pop, ... 
        "roulette", ... 
        "PMX", ... 
        "genitor", ... 
        "exchange" ...
    );
    genetic = run(genetic, 1, 30);
end

% ----------------------------------
% --------Parent Selection----------
% ----------------------------------
n_parents = [4 8 10 16 20];
S = [1 1.2 1.5 1.6 2];
for spm = select_parent_methods
    for n = n_parents
        if strcmp(spm, "rank")
            rng(12345);
            genetic = Genetic( ...
                N, ... 
                20, ... 
                spm, ... 
                'PMX', ... 
                'genitor', ... 
                'exchange', ...
                'exp-rank', ...
                n ...
            );
            genetic = run(genetic, 1, 30);
            for s = S
                rng(12345);
                genetic = Genetic( ...
                    N, ... 
                    20, ... 
                    spm, ... 
                    'PMX', ... 
                    'genitor', ... 
                    'exchange', ...
                    'lin-rank', ...
                    n, ...
                    s ...
                );
                genetic = run(genetic, 1, 30);
            end
        else
            rng(12345);
            genetic = Genetic( ...
                N, ... 
                20, ... 
                spm, ... 
                'PMX', ... 
                'genitor', ... 
                'exchange', ...
                'exp-rank', ...
                n ...
            );
            genetic = run(genetic, 1, 30);
        end
    end
end

% ----------------------------
% --------Crossover-----------
% ----------------------------
for com = cross_over_method
    rng(12345);
    genetic = Genetic( ...
        N, ... 
        20, ... 
        'roulette', ... 
        com, ... 
        'genitor', ... 
        'exchange' ...
    );
    genetic = run(genetic, 1, 30);
end

% ----------------------------
% --------Survivours----------
% ----------------------------
for ssm = survivor_select_method
    rng(12345);
    genetic = Genetic( ...
        N, ... 
        20, ... 
        'roulette', ... 
        'PMX', ... 
        ssm, ... 
        'exchange' ...
    );
    genetic = run(genetic, 1, 30);
end

% ----------------------------
% --------Mutations-----------
% ----------------------------
m_prob = [0.2 0.4 0.5 0.6 0.8 1];
for m = mutations
    if ~strcmp(m, "none")
        for p = m_prob
            rng(12345);
            genetic = Genetic( ...
                N, ... 
                20, ... 
                'roulette', ... 
                'PMX', ... 
                'genitor', ... 
                m ...
            );
            genetic.prob_mutation = p;
            genetic = run(genetic, 1, 30);
        end
    else
        rng(12345);
        genetic = Genetic( ...
            N, ... 
            20, ... 
            'roulette', ... 
            'PMX', ... 
            'genitor', ... 
            m ...
        );
        genetic = run(genetic, 1, 30);
    end
end

% -----------------------------
% --------Final Model----------
% -----------------------------
rng(12345);
genetic = Genetic( ...
    100, ... 
    260, ... 
    'roulette', ... 
    'PMX', ... 
    'genitor', ... 
    'exchange' ...
);
genetic.n_parents = 180;
genetic = run(genetic, 2, 30);

